#!/bin/bash
echo "The script requires sudo to copy global configuration files..."

while [ "$1" != "" ]; do
    case $1 in
        f | --fonts)
            shift
            bash ./install-terminus-font.sh # run installation script
            ;;
        *)
            ;;
    esac
    shift
done

# Copy these files to homedir
echo -n "Copying files... "
cp -r .xinitrc \
    .xsession \
    .git/ \
    .gitignore \
    .vim/ \
    .vimrc \
    .config/ \
    .inputrc \
    .bash_profile \
    .bashrc \
    .Xresources \
    bin/ \
    $HOME
echo "Done!"

source $HOME/.bash_profile
touch $HOME/.bash_private

echo -n "Installing Xorg files... "
sudo mkdir -p /etc/X11/xorg.conf.d
sudo cp 00-keyboard.conf /etc/X11/xorg.conf.d/
echo "Done!"

echo -n "Running Vim Bundle... "
mkdir -p $HOME/.vim/bundle
if [ ! -d "$HOME/.vim/bundle/Vundle.vim" ]; then
    git clone https://github.com/vundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi
vim +PluginInstall +qall
echo "Done!"
